# Generated by Django 3.0.3 on 2020-02-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='post',
        ),
    ]
