# Generated by Django 3.0.3 on 2020-03-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0002_auto_20200229_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.BooleanField(default=False),
        ),
    ]
